### ISSUE TITLE
README.md contains example of deprecated code

### ISSUE THREAD

**Issue by igalbk** [wavefrontHQ/wavefront-opentracing-sdk-java#100]
See the Usage section in README.md
`
  // Step 2. Create a WavefrontSender for sending trace data via a Wavefront proxy.
  //         Assume you have installed and started the proxy on <proxyHostname>.
  WavefrontSender wavefrontSender = new WavefrontProxyClient.Builder(<proxyHostname>).
        metricsPort(2878).distributionPort(2878).tracingPort(30000).build();
`
WavefrontProxyClient is deprecated, would be good to include an updated example.

**Comment by haosong** [comment]
Discussed with @shavidissa offline, will update the README with up to date example.

**Comment by shavidissa** [comment]
Thank you! Forgot to close the issue. This was fixed with [1].

[1] https://github.com/wavefrontHQ/wavefront-opentracing-sdk-java/pull/101
