### ISSUE TITLE
Guava vulnerability coming from stale wavefront-sdk-java

### ISSUE THREAD

**Issue by igalbk** [wavefrontHQ/wavefront-opentracing-sdk-java#106]
In [wavefront-sdk-java Pull Request 180](https://github.com/wavefrontHQ/wavefront-sdk-java/pull/180) the Guava version was updated and a new release [2.6.4](https://github.com/wavefrontHQ/wavefront-sdk-java/releases/tag/v2.6.4) is available.
The request is to update the dependency in wavefront-opentracing-sdk-java in order to resolve guava vulnerability and create a new release

**Comment by oppegard** [comment]
This is addressed by #108, which updates the transitive guava dependency to 30.1.1-jre. We've released  v2.1.6 of wavefront-opentracing-sdk-java which includes this update.
