### ISSUE TITLE
Thread leak on sender threads

### ISSUE THREAD

**Issue by mhalbritter** [wavefrontHQ/wavefront-opentracing-sdk-java#137]
Hi, while working on `micrometer-tracing`, i discovered a thread leak in a component which is based on your span senders. I think the original senders (your senders) have the same problem. See https://github.com/micrometer-metrics/tracing/pull/12 for details and for a fix.

**Comment by oppegard** [comment]
Thank you for reporting this issue! I've added it to our backlog and we'll prioritize for investigation.
