### ISSUE TITLE
Baggage items are not propagated from parent's span context 

### ISSUE THREAD

**Issue by rgeorgiev** [wavefrontHQ/wavefront-opentracing-sdk-java#51]
According to OpenTracing spec: https://github.com/opentracing/specification/blob/master/specification.md

All baggage items has to be propagated to all child SpanContexts, but looking at 
WavefrontSpanBuilder.createSpanContext()  they are not propagated.

**Comment by vikramraman** [comment]
Thanks for raising this issue @rgeorgiev. We will address it for the next release.

**Comment by vikramraman** [comment]
Done.
