### ISSUE TITLE
X-debug-id in HTTP headers should always be sampled

### ISSUE THREAD

**Issue by vikramraman** [wavefrontHQ/wavefront-opentracing-sdk-java#68]
Similar to https://github.com/jaegertracing/jaeger-client-java/blob/02252d99aa3ec2e7686e2ca7f92ede99013528eb/README.md#via-http-headers the WavefrontTracer should ensure traces created from requests with a `debug-id` in the HTTP headers are always sampled.

**Comment by haosong** [comment]
Close this for now. Feel free to use `debug=true` tag in span to mark the span always get sampled.
